# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 18:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('created', models.DateTimeField(verbose_name=datetime.datetime(2017, 9, 11, 18, 9, 29, 401368, tzinfo=utc))),
                ('title', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('post_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.BlogPost')),
            ],
        ),
    ]
