# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 21:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 9, 11, 21, 16, 10, 576340, tzinfo=utc)),
        ),
    ]
